### ISSUE TITLE
genConfirmationCode недостаточно случайный

### ISSUE THREAD

**Issue by antonkalinin-ml** [fullstack-development/haskell-starter-kit#14]
`AppName.Domain.PhoneVerification.genConfirmationCode` не возвращает новое значение случайного генератора и дважды использует одно значение генератора. Недостаточная рандомность может привести к уязвимости - коды подтверждения станут предсказуемыми.

`shuffle'` использует исходный генератор, но не возвращает новое значение. Этот же генератор подается на вход `randomR` в функции `generate`.

Непонятно, для чего двойное перемешивание - сначала в `shuffle'` для случайной перестановки 10 цифр, а затем в `generate` для получения символов по случайным индексам из перемешанного источника. Мне кажется, одного `generate` вполне хватило бы, случайную цифру можно сгенерировать при помощи `randomR ('0', '9')`, они все будут выбраны независимо. И `randomR` возвращает новый генератор, так что его можно вернуть из `genConfirmationCode`.

**Comment by Znack** [comment]
Вот это крутое замечание, странно, что мы дважды одно значение использовали. Можешь плиз ПР создать на эту тему?

**Comment by antonkalinin-ml** [comment]
Вроде поправил.

И еще, мне кажется, стоит использовать криптографический генератор, они несложные в использовании (тот же интерфейс RandomGen) и производительные.
