### ISSUE TITLE
Ошибки при развертывании проекта

### ISSUE THREAD

**Issue by antonkalinin-ml** [fullstack-development/haskell-starter-kit#16]
Последовательно иду по шагам в README.md и получаю ошибки. До шага с миграциями все проходит успешно.

На шаге `./migration/run.sh` ошибка:

    File liquibase.properties not found

`stack run` и `stack exec haskell-starter-kit-exe` оба выдают следующее:

```
{"appInstanceName":"AppName","severity":"Info","message":"Starting application...","timestamp":"2021-03-29T09:45:28.388407263Z","trace":"[Lib.runLogExample#58] "}
{"appInstanceName":"AppName","severity":"Debug","message":"Here is how we work!","timestamp":"2021-03-29T09:45:28.388619931Z","trace":"[Lib.runLogExample#59] "}
{"appInstanceName":"AppName","severity":"Debug","message":"starting server","timestamp":"2021-03-29T09:45:28.388675734Z","trace":"[Lib.logDebug#30] "}
haskell-starter-kit-exe: ParseError "" "no such variable \"DB_HOST\""
```

При этом `stack build` успешно билдит, `make deps` и `make run` тоже работают. docker.io и docker-compose установлены. Файлы `.env` и `config/local.conf` скопированы из темплейтов. Содержимое `.env`:

```
POSTGRES_HOST_AUTH_METHOD=md5
DB_HOST=localhost
DB_PORT=5432
POSTGRES_USER=kav
POSTGRES_PASSWORD=
POSTGRES_DB=appnamedb
```

Содержимое `config/local.conf`:

```
database {
  host = "$(DB_HOST)"
  port = "$(DB_PORT)"
  name = "$(POSTGRES_DB)"
  user = "$(POSTGRES_USER)"
  pass = "$(POSTGRES_PASSWORD)"
  pool_limit = 10
}

web_server {
  port = 8080
}

auth {
  key_path = "./keys/auth-key"
}

log {
  app_instance_name = "AppName"
  log_to_stdout = on
  log_level = "Debug"
}

app {
  domain_specific = "SOME_DOMAIN_SPECIFIC_PARAM"
}
```

Система Linux debian bullseye.

**Comment by antonkalinin-ml** [comment]
По этой причине не работает `stack test` и я не могу удостовериться, что на моих доработках проходят тесты :)

```
haskell-starter-kit> test (suite: haskell-starter-kit-test)

haskell-starter-kit-test: ParseError "" "no such variable \"DB_HOST\""

haskell-starter-kit> Test suite haskell-starter-kit-test failed
Test suite failure for package haskell-starter-kit-0.1.0.0
    haskell-starter-kit-test:  exited with: ExitFailure 1
Logs printed to console
```
```

**Comment by Znack** [comment]
кстати мы забыли добавить README: `source .env` перед `stack build|repl` потому что переменные из .env только после этой команды попадут в само окружение :(

**Comment by antonkalinin-ml** [comment]
`source .env` не помогает, недостает команды `export` перед присваиваниями в `.env`. Я отредактировал файл вот так и `stack run`/`stack test` заработали:

```
export POSTGRES_HOST_AUTH_METHOD=md5
export DB_HOST=localhost
export DB_PORT=5432
export POSTGRES_USER=kav
export POSTGRES_PASSWORD=
export POSTGRES_DB=appnamedb
```

Но я так понимаю, `.env` нельзя в таком виде оставлять, `make run` выдает ошибку.
И проблема с миграциями остается.

**Comment by Znack** [comment]
Да, согласен, так не срабоатет, потому что там нет инструкции `export`, но и добавлять её не стоит :(

Можно тогда команду `source .env` заменитть на `export $(cat .env | xargs)` — [по сути эффект тот же](https://stackoverflow.com/a/20909045), окружение наполнится переменными из .env, и не надо добавлять `export` перед каждой :)

**Comment by antonkalinin-ml** [comment]
Хорошо, одну проблему решили. В README добавлю строчку про `export $(xargs < .env)`.

Что касается миграций, то в ридми не сказано про копирование файла liquibase.properties, нужно добавить. Однако после копирования и правки liquibase.properties `./migrations/run.sh` все равно не работает, выдает ошибку:

```
Mar 30, 2021 12:29:26 PM org.postgresql.Driver connect
SEVERE: Connection error: 
org.postgresql.util.PSQLException: The connection attempt failed.
        at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:275)
        at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
        at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:194)
        at org.postgresql.Driver.makeConnection(Driver.java:450)
        at org.postgresql.Driver.connect(Driver.java:252)
        at liquibase.database.DatabaseFactory.openConnection(DatabaseFactory.java:239)
        at liquibase.database.DatabaseFactory.openDatabase(DatabaseFactory.java:151)
        at liquibase.integration.commandline.CommandLineUtils.createDatabaseObject(CommandLineUtils.java:85)
        at liquibase.integration.commandline.Main.doMigration(Main.java:958)
        at liquibase.integration.commandline.Main.run(Main.java:188)
        at liquibase.integration.commandline.Main.main(Main.java:103)
Caused by: java.net.UnknownHostException: host.docker.internal
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at org.postgresql.core.PGStream.<init>(PGStream.java:68)
        at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:144)
        ... 10 more
```

Файл migrations/liquibase.properties:

```
classpath: /opt/jdbc/postgres-jdbc.jar
driver: org.postgresql.Driver
url: jdbc:postgresql://host.docker.internal:5432/appnamedb
username: kav
password:
changeLogFile: changelog.xml
logLevel: info
```

Судя по ошибке, не может найти host.docker.internal. `make run` я предварительно запускал.

**Comment by Znack** [comment]
Хм, странно. А у тебя база в докер контейнере запущена в это время? Она порт 5432 нормально проксирует? Ты можешь извне докера подключиться например просто через psql к этой базе?

**Comment by antonkalinin-ml** [comment]
> Хм, странно. А у тебя база в докер контейнере запущена в это время? Она порт 5432 нормально проксирует? Ты можешь извне докера подключиться например просто через psql к этой базе?

Предварительно запускал `make run`, запускал миграции - ошибка.
Останавливал `make run` по Ctrl+C - то же.

Подключиться к базе могу по порту 5431 (не 5432), все правильно? В ридми указано коннектиться именно на 5431:
`psql -U myuser -d appnamedb -p 5431 -h 127.0.0.1 -W`

На 5432 у меня работал постгрес, установленный на машине. Я его отключил, перезапустил сервис докера, удостоверился, что порты 5432 и 5431 не заняты, запустил`make run` - ошибка та же. `lsof` показывает, что докером занят порт 5431, а 5432 свободен.

**Comment by Znack** [comment]
А, ну да, 5431, Стас же специально сделал, чтобы с локальным постгресом не конфликтовало. А почему тогда в .env у тебя `DB_PORT=5432`? :) Там в общем точно проблема не из-за портов? Liquibase точно может дотянуться до базы?

**Comment by antonkalinin-ml** [comment]
> А почему тогда в .env у тебя DB_PORT=5432? :)

Потому что в .env.template то же самое, я его просто скопировал. Правка 5432 на 5431 не помогла.
Как я понимаю, внутри докера постгрес по-прежнему слушает 5432, а наружу этот порт выводится на 5431. Это в docker-compose.yaml есть.

> Там в общем точно проблема не из-за портов? Liquibase точно может дотянуться до базы?

А как это проверить? Думаю, что не из-за портов - жалуется на неизвестный хост host.docker.internal, копать надо скорее в эту сторону.

**Comment by Sergey111991KV** [comment]
у меня что-то типа того было, я поменял на это в docker-compose.yaml
services:
  db:
    image: postgres:latest
    container_name: placid_db
    environment:
      - POSTGRES_DB=placid_dev
      - POSTGRES_USER=placid_user
      - POSTGRES_PASSWORD=placid_pass
    ports: 
      - 5431:5432
    volumes:
      - pg-data:/var/lib/postgresql/data 
а еще в локальных конфигах database {
  host = "localhost"
  port = "5431"
  name = "placid_dev"
  user = "placid_user"
  pass = "placid_pass"
  pool_limit = 10
}
ну и абсолютно все поубивал и очистил в докере 
docker-compose down
docker volume prune

**Comment by Znack** [comment]
А можешь плиз полную конфигурацию скинуть, как у тебя стало? Главное, чтобы в `liquibase.properties` правильно выставлено было :)

> жалуется на неизвестный хост host.docker.internal,

Хм, возможно проблема в этом, если у тебя не мак. Вроде на маках норм с host.docker.internal. Если не мак, то надо гуглить, как из докера к локалхосту машины можно пробраться, я помню как-то прокидывал сеть для этого, но детали забыл уже :(

**Comment by antonkalinin-ml** [comment]
Разобрался, скоро будет патч.

**Comment by antonkalinin-ml** [comment]
Открыл ревью https://github.com/fullstack-development/haskell-starter-kit/pull/20 . Спасибо вам за помощь, натолкнули на правильные мысли.

Я не стал добавлять инструкцию по `export $(xargs < .env)`, потому что она нужна только для `stack test`, а тесты на самом деле игнорируют конфиг и значения переменных могут быть абсолютно любыми. Думаю, надо отдельно исправить, чтобы конфиг не парсился в тестах.

> а еще в локальных конфигах database {
host = "localhost"
port = "5431"
name = "placid_dev"
user = "placid_user"
pass = "placid_pass"
pool_limit = 10
}

Насколько я понимаю работу докера, контейнер с проектом лазит в контейнер с постгресом по внутренней сети докера, поэтому ему не нужен локалхост и порт 5431. Порт 5431 сделали вроде как только для liquibase, чтобы запускать миграции, поскольку liquibase не имеет доступа к сети между сервером и постгресом.

**Comment by antonkalinin-ml** [comment]
Думаю, кто-то из ребят ошибся с портом в liquibase.properties, поскольку у него на машине локально крутился свой постгрес и миграции прекрасно отработали, только не в той базе :). А может, просто забыли скопировать порт в liquibase.template.properties. В связи с этим было бы здорово, чтобы сервер сам запускал миграции на старте или хотя бы проверял необходимость в проведении миграции - а то выполнил миграции и понятия не имеешь, возымели они эффект или нет, не ошибся ли ты базой. По-моему, при запуске серверу абсолютно все равно, были там миграции или нет, он в базу не ходит.

**Comment by kelizarov** [comment]
> В связи с этим было бы здорово, чтобы сервер сам запускал миграции на старте или хотя бы проверял необходимость в проведении миграции - а то выполнил миграции и понятия не имеешь, возымели они эффект или нет, не ошибся ли ты базой. По-моему, при запуске серверу абсолютно все равно, были там миграции или нет, он в базу не ходит.

Вот тут сложно сказать как можно было настроить. Можно попробовать поиграться с docker-compose чтобы тот запускал докер с liquibase и запускал миграции.

**Comment by Znack** [comment]
> Насколько я понимаю работу докера, контейнер с проектом лазит в контейнер с постгресом по внутренней сети докера, поэтому ему не нужен локалхост и порт 5431. Порт 5431 сделали вроде как только для liquibase, чтобы запускать миграции, поскольку liquibase не имеет доступа к сети между сервером и постгресом.

Не, я так понял, у нас просто недопонимания :) По идее у нас вся работа с базами должна быть по 5431, если где-то встречается 5432, то его надо поменять на 5431. У нас просто есть два варианта разворачивания: через докер компоуз для тех, кому бекенд нужен просто, чтобы API получить локально (для мобильщиков), а для бекендеров нужно сам проект разворачивать без докера, тут докер компоуз уже не нужен, нужно через докер поднимать только базу. И надо чтобы в обоих случаях наш бекенд ходил в базу по 5431, возможно мы это где-то потеряли :)

**Comment by Znack** [comment]
Но судя по всему в [ПР-е](https://github.com/fullstack-development/haskell-starter-kit/pull/20) ты все правильно сделал, нам как раз надо было 5431 везде настроить :)

**Comment by antonkalinin-ml** [comment]
Так бы в ридми и написали :). Постараюсь поправить.

**Comment by Znack** [comment]
Да мы в супер спешке делали, не очень думали о том, как грамотно ридми написать, писали только супер необходимое все 😞

**Comment by antonkalinin-ml** [comment]
> По идее у нас вся работа с базами должна быть по 5431, если где-то встречается 5432, то его надо поменять на 5431. У нас просто есть два варианта разворачивания: через докер компоуз для тех, кому бекенд нужен просто, чтобы API получить локально (для мобильщиков), а для бекендеров нужно сам проект разворачивать без докера, тут докер компоуз уже не нужен, нужно через докер поднимать только базу. И надо чтобы в обоих случаях наш бекенд ходил в базу по 5431, возможно мы это где-то потеряли :)

Если коннектиться всегда к порту 5431, то хост все равно будет разный: снаружи докера это localhost, изнутри host.docker.internal. Придется править `.env` в зависимости от того, где мы запускаем сервер. У вас есть идеи, как это решается, не считая инструкций в README и двух шаблонов конфига?

**Comment by Znack** [comment]
А зачем именно `.env` править? Мы можем просто при запуске из докера в Dockerfile указать хост, но ещё лучше это сделать в docker-compose, прокинуть просто оттуда энвом хост базы. Просто так запускать докер контейнер одного сервера мне пока не очень понятно зачем вообще, обычно мы либо базу отдельно поднимаем (если это бекендер и он стеком уже локально весь бекенд разворачивает), либо через докер-компоуз (если это например фронтендер, которому надо быстро бекенд поднять локально)

**Comment by antonkalinin-ml** [comment]
> Просто так запускать докер контейнер одного сервера мне пока не очень понятно зачем вообще, обычно мы либо базу отдельно поднимаем (если это бекендер и он стеком уже локально весь бекенд разворачивает), либо через докер-компоуз (если это например фронтендер, которому надо быстро бекенд поднять локально)

Я как раз об этом :). Как я понял, есть два варианта запуска:
- для фронтендеров: и база, и сервер в докере. Порт постгреса внутри контейнера 5432, на него можно попасть по доменному имени `db`, доступному внутри сети, которую создает docker-compose. Таким образом, DB_HOST=db и DB_PORT=5432. Это именно та конфигурация, которая описана в `.env.template`.
- для бэкендеров: база в докере, сервер нет. Порт постгреса внутри контейнера 5432, поэтому попасть на него напрямую не из докера нельзя. Он мапится на порт 5431 локалхоста, поэтому DB_HOST=localhost и DB_PORT=5431. Это не совпадает с конфигурацией в `.env.template`.

Таким образом, в зависимости от того, как запущен сервер, меняется порт и хост постгреса. В обоих случаях постгрес запускается в докере.

Можно попадать в постгрес всегда по порту 5431, но это порт на локалхосте (напомню, постгрес работает в докере, а `localhost:5431` мапится на `db:5432`). Если сервер запущен локально, то он должен идти на `localhost:5431`, а если внутри докера - он не имеет доступа к локахлосту и должен использовать `host.docker.internal:5431`.

> А зачем именно .env править? Мы можем просто при запуске из докера в Dockerfile указать хост, но ещё лучше это сделать в docker-compose, прокинуть просто оттуда энвом хост базы

Объясни пожалуйста подробнее :). Как прокинуть энвом хост до базы, не меняя энв? Мы про `.env` говорим?
Как мы выяснили в https://github.com/fullstack-development/haskell-starter-kit/pull/20#discussion_r606817614, простая замена порта в `.env` не работает.

**Comment by Znack** [comment]
> для фронтендеров: и база, и сервер в докере. Порт постгреса внутри контейнера 5432, на него можно попасть по доменному имени db, доступному внутри сети, которую создает docker-compose. Таким образом, DB_HOST=db и DB_PORT=5432. Это именно та конфигурация, которая описана в .env.template.

я думаю тогда проблема в этом — у нас тут используется 5432 и из-за этого неконсистентость. Давай везде 5431 по умолчанию выставим, пусть внутри докер-компоуза тоже к базе по 5431 ходят :)

Можно вообще прямо на уровне образа постгреса сказать энвами, чтобы он сразу базу на 5431 поднимал


> Можно попадать в постгрес всегда по порту 5431, но это порт на локалхосте (напомню, постгрес работает в докере, а localhost:5431 мапится на db:5432). Если сервер запущен локально, то он должен идти на localhost:5431, а если внутри докера - он не имеет доступа к локахлосту и должен использовать host.docker.internal:5431.

А вчера же кстати удалось в итоге по localhost попасть из докера? или по айпишнику только?

>> А зачем именно .env править? Мы можем просто при запуске из докера в Dockerfile указать хост, но ещё лучше это сделать в docker-compose, прокинуть просто оттуда энвом хост базы
>
> Объясни пожалуйста подробнее :). Как прокинуть энвом хост до базы, не меняя энв? Мы про .env говорим?

Ну я тут про то, что .env это же просто шаблон для удобства, он сам по себе до применения комнады `source` не имеет никакой силы. И мы можем иногда переопределять значения из `.env` просто переопределяя свои переменные прямо в самом окружении. Хз, насколько понятно выразился 😄  Но у меня ощущение, что это уже в любом случае неактуально, если мы просто везде на 5431 переедем :)

**Comment by antonkalinin-ml** [comment]
> А вчера же кстати удалось в итоге по localhost попасть из докера? или по айпишнику только?

Не получилось :(. По айпишнику я не пробовал, но и так понятно, что со 127.0.0.1 (aka localhost) не выйдет, затея лишена смысла.

Понял идею с прокидыванием окружения. Прямо в Makefile можно переопределить часть переменных, чтобы сервер в докере находил базу. Но тут начинается неразбериха с конфигами - в .env написано одно, а по факту хост базы переопределяется в Makefile, что может ввести в заблуждение. У нас .env предполагается копировать и игнорить гитом, что создает иллюзию полной конфигурабельности .env, хотя на те настройки лучше не дышать, если хочешь просто развернуть проект для разработки :).

Надо подумать, как упростить работу с конфигами:
- сделать скрипт создания локальных конфигов
- исключить дублирование между конфигами и желательно сложить все настройки в 1-2 файла. Это к вопросу об использовании Dhall и генерации конфигов из какого-то одного, большого конфига.
- мне не нравится, что кучу конфигов предполагается копировать и игнорить гитом. Если темплейт конфига в гите изменится, юзер забудет обновить локальный конфиг. И наоборот, легко забыть перенести настройки из локального конфига в темплейт - у тебя проект билдится и работает, все замечательно, только у коллег работать не будет. Хорошо бы иметь поддержку импортируемых конфигов и локально создавать конфиг-заглушку вида `import default.conf` или указывать вручную имя конфига при запуске, если хочется не дефолтный, а другой, или переопределять часть настроек в переменных среды.
- часть настроек, например окружение докера, не имеет смысла править локально, и копировать их незачем. docker-compose умеет опцию `--env-file`, так что для докера и локального запуска у нас может быть сколько угодно енвов, хранимых в гите, на которые может ссылаться Makefile.

Я над этим попозже еще подумаю.

**Comment by antonkalinin-ml** [comment]
Про конфиги создал задачу https://github.com/fullstack-development/haskell-starter-kit/issues/27

**Comment by Znack** [comment]
> Не получилось :(. По айпишнику я не пробовал, но и так понятно, что со 127.0.0.1 (aka localhost) не выйдет, затея лишена смысла.

Не, я про айпишник `172.17.0.1` из того треда с стэковерфлоу. У меня с ним сработало просто на aws codebuild :)

**Comment by Znack** [comment]
> переопределяется в Makefile, что может ввести в заблуждение

ну тут да, для меня просто это норм, так как я к .env отншусь как к дефолтным настройкам, которые могут быть переопределены в разных кейсах :)

**Comment by antonkalinin-ml** [comment]
> > Не получилось :(. По айпишнику я не пробовал, но и так понятно, что со 127.0.0.1 (aka localhost) не выйдет, затея лишена смысла.
> 
> Не, я про айпишник `172.17.0.1` из того треда с стэковерфлоу. У меня с ним сработало просто на aws codebuild :)

Ага, работает, причем и при запуске сервера из докера, и локально. Но я не в восторге от идеи указывать непонятно откуда взявшиеся айпишники, его ни в одном конфиге нет. Можно этим пользоваться, если недолго, но лучше бы найти постоянное, нормальное решение. Это деталь реализации докера, который, как мы знаем, работает по-разному в зависимости от платформы, и кто знает, что в нем поменяется через год.

**Comment by antonkalinin-ml** [comment]
Вариант с доопределением хоста в переменной среды выглядит неплохо. Можно совсем не указывать хост в .env, а всегда указывать в переменной среды, либо использовать два файла .env, у нас Makefile и скрипты это позволяют. Если хост забудут указать, будет понятная ошибка "DB_HOST не определен", а не загадочная "не могу подключиться к БД".

**Comment by Znack** [comment]
> Можно этим пользоваться, если недолго, но лучше бы найти постоянное, нормальное решение. Это деталь реализации докера, который, как мы знаем, работает по-разному в зависимости от платформы, и кто знает, что в нем поменяется через год.

Ага, я согласен что это костыль, пока вставить, чтобы хоть как то разработку в предсказуемое время можно было начинать :)

> Если хост забудут указать, будет понятная ошибка "DB_HOST не определен", а не загадочная "не могу подключиться к БД".

С этим тоже согласен :)
