### ISSUE TITLE
Автоформат меняет код, который я не трогал. Настроить CI или хуки?

### ISSUE THREAD

**Issue by antonkalinin-ml** [fullstack-development/haskell-starter-kit#17]
Должно быть, ребята забывают прогнать форматтер после редактирования либо мы используем разные версии ormolu. Я поставил 0.0.3.1.

Предлагаю подумать насчет CI, чтобы блокировал мержи, пока ошибки формата не исправят. Казалось бы, для этого проекта не стоит заморачиваться, но я уже потратил сколько-то минут на удаление лишних изменений, внесенных форматтером, и, вероятно, буду это делать еще не раз. Настройка CI это полезный опыт, и скорее всего, много времени она не займет.

Еще вариант - хуки, срабатывающие при коммите, которые автоматически форматируют. Не нужно настраивать CI, но взамен надо как-то убедить разработчиков установить хуки (1 команда в консоли после клона репы) или прописать установку хуков куда-нибудь в `make`. Хуки можно обойти опцией в коммите. Скрипт для хуков будет достаточно сложный и местами глюкавый (у меня был :)), если мы хотим, чтобы он умел править изменения, частично добавленные в индекс гита. Для CI скрипт будет проще - прогнал по всему проекту и подсветил ошибки, так что я больше за вариант с CI.

В будущем CI и хуки можно комбинировать, чтобы хуки форматировали при коммите, не отвлекая человека, а CI делал финальную проверку.

**Comment by Znack** [comment]
Я тоже за вариант с CI. А причина почему у нас некоторые файлы неотформатированны проста: там и правда забывали иногда запускать форматтер те, у кого он не настроен по умолчанию (у меня стоит на auto save, я доволен, не знаю зачем вручную его гонять). Но CI бесплатный для опенсорс проекта, тем более тут ещё и тесты есть — я только за :)

**Comment by kelizarov** [comment]
Я за то что чтобы начать с гит-хуков. Не уверен что CI будет на всез проектах которые мы будем стартовать, а хуки хотя бы на локальном уровне предостерегут от коммитов не отфрамотированного кода. Но там проблема может возникнуть что у всех версия может отличаться, возможно можно пока просто в ридми указать какой версией форматироть. 

Но можно и это исправить если бы мы использовать никс окружение для проекта, и в этом окружении использовали нам нужный форматтер для этого.

**Comment by antonkalinin-ml** [comment]
> Но там проблема может возникнуть что у всех версия может отличаться, возможно можно пока просто в ридми указать какой версией форматироть.

Можно попробовать прописать форматтер в зависимости проекта (там можно и версию указать) и запустить через stack exec. Я так не пробовал, но кажется, что это близко к тому, чтобы работать. Мы можем указать либу в зависимостях, и можем сделать проект из нескольких пекеджей - почему должно быть нельзя приделать к проекту пекедж с исполняемым файлом как зависимость.

**Comment by kelizarov** [comment]
Ну лично я бы хотел чтобы наш проект собирался через nix, мне кажется его польза с reproducible builds и фиксированием зависимостей и тулзов на проекте перевешивает stack. Хоть он будет немного тяжелее в настроке :)

**Comment by Znack** [comment]
Ну nix в любом случае не в ближайшем будущем, так что пока лучше решиться, что делаем с форматтером через стэк :)

Хуки мне не нравятся тем, что каждый коммит ждать проверку не хочется :(

**Comment by antonkalinin-ml** [comment]
> Хуки мне не нравятся тем, что каждый коммит ждать проверку не хочется :(

В смысле? Не придется ждать, исходники автоматически правятся во время коммита, и только те, что изменились. Пару лет так работал, все устраивало (проект на ObjC).

**Comment by antonkalinin-ml** [comment]
Писать хороший скрипт для хуков мне будет лень, и это просто долго, а CI можно быстро настроить, есть готовые примеры и плагин ormolu для гитхаба, вот буквально скопипастить и сохранить.

**Comment by Znack** [comment]
> В смысле? Не придется ждать, исходники автоматически правятся во время коммита, и только те, что изменились. Пару лет так работал, все устраивало (проект на ObjC).

Хм, может у меня был какой-то кривой опыт, но я по минуте-две ждал хуки форматтера, пока они отработают нормально. Ну и я не уверен, что стоит именно автоформаттер запускать в таком случае, я бы запускал именно на проверку с форматтером и если он выдал расхождения, то просто коммит отменять, не форматить в фоне. Если форматить в фоне, то есть вероятность случайно закоммитить что-то невалидное, я за то чтобы все было по максимуму явное :)

**Comment by antonkalinin-ml** [comment]
В хуках можно выдавать только ошибку формата, а не форматировать.

В прошлом проекте мы так жили, и было много надоедливых ошибок при коммите, потому что наш форматтер форматировал так, как руками не напишешь (но это был clang-format для ObjC с его километровыми строками, который интеллектуально упихивал строки в заданную длину). Коллеги жаловались, что перед каждым коммитом нужно руками прогонять форматтер, заново набирать заголовок коммита. В итоге сделали автоформат - стало очень круто, пропал значительный отвлекающий фактор. В том форматтере были баги, но проявлялись очень редко, они заключались в неправильной расстановке пробелов из-за ошибок разбора, легко чинились директивами форматтера и на семантику кода не влияли, и улучшения были настолько значительными, что на недостатки никто особо внимания не обращал :). В хаскеле пробелы влияют на семантику, так что в теории баг форматтера может внести незаметный баг в код, если он скомпилируется. Я не знаю, насколько серьезно нужно к этому относиться. При каждом коммите получать сообщение об ошибке, гонять форматтер, читать дифф и повторять коммит настолько раздражает, что мне кажется, если форматтер и внесет ошибку когда-нибудь, раз в год (и код скомпилируется!), ее все равно могут не заметить. Возможно, надо почитать код форматтера и выяснить, как он форматирует, сохраняет ли он поток лексем неизменным, например.

Можно сделать прогон формата при сохранении, но это неудобно, если настроен автосейв. Набираешь текст, задумался на секунду - автосейв - курсор улетает не пойми куда, в начало функции, или вообще ошибка высвечивается - код недописан, он не компилируется и парсер его не понимает.

Что касается скорости, вызов ormolu на всем проекте у меня занимает полсекунды, а на одном файле - 55 мс, так что сам форматтер не слишком тормозит (а еще его можно запускать параллельно, по числу ядер - `xargs -P` умеет). Если хук будет форматировать только измененные файлы, которых обычно всего несколько штук, то никаких проблем не возникнет. Возможно, у вас форматировался весь проект на каждом коммите. У нас задержка при старте редактора была тоже в районе секунды, точно не минуты, скрипт для хука был написан на питоне.

Еще у нас была проблема того, что половина людей гайдлайны не читала и не устанавливала хуки :), хотя инструкция по хукам шла первой строчкой и состояла в установке clang-format и запуске скрипта однократно. Приходилось персонально к каждому подходить и разъяснять. А все потому, что не было CI и проверки формата - иначе люди сами бы побежали ставить хуки, потому как проще сразу форматировать при коммите правильно, чем делать ребейз и править историю. Это не будет проблемой, если на проекте немного людей и новички приходят редко.

**Comment by Znack** [comment]
Ага, со всем согласен, звучит справедливо :) Вмержил ПР, я думаю, что на практике будет всё ок :)
